# Generated by Django 4.2.4 on 2023-08-31 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fnasc', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('dni', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'CLIENTE',
                'verbose_name_plural': 'CLIENTES',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('contacto', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('cuit', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'PROVEEDOR',
                'verbose_name_plural': 'PROVEEDORES',
            },
        ),
        migrations.CreateModel(
            name='RubroProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'RUBRO',
                'verbose_name_plural': 'RUBROS',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AppTercer.proveedor')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AppTercer.rubroprod')),
            ],
            options={
                'verbose_name': 'PRODUCTO',
                'verbose_name_plural': 'PRODUCTOS',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('comprador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='AppTercer.cliente')),
                ('producto', models.ManyToManyField(to='AppTercer.producto')),
            ],
            options={
                'verbose_name': 'ORDEN COMPRA',
                'verbose_name_plural': 'ORDENES COMPRA',
            },
        ),
    ]
