# Generated by Django 4.2.4 on 2023-08-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTercer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rubroprod',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cuit',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rubroprod',
            name='nombre',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
