# Generated by Django 4.2.4 on 2023-08-31 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppTercer', '0002_remove_cliente_id_remove_proveedor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubroprod',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='comprador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='AppTercer.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cuit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rubroprod',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
